-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 19:58:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login` DEFAULT CHARACTER SET utf8 ;
USE `login` ;

-- -----------------------------------------------------
-- Table `login`.`discente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`discente` (
  `matricula` BIGINT(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `nome_aluno` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`coordenacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`coordenacao` (
  `cod_siape` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `coordenacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_siape`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`curso` (
  `idcurso` INT NOT NULL,
  `nome_curso` VARCHAR(50) NOT NULL,
  `departamento_cod_siape` INT NOT NULL,
  `discente_matricula` BIGINT(15) NOT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_departamento_idx` (`departamento_cod_siape` ASC),
  INDEX `fk_curso_discente1_idx` (`discente_matricula` ASC),
  CONSTRAINT `fk_curso_departamento`
    FOREIGN KEY (`departamento_cod_siape`)
    REFERENCES `login`.`coordenacao` (`cod_siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_discente1`
    FOREIGN KEY (`discente_matricula`)
    REFERENCES `login`.`discente` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`requerimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`requerimento` (
  `idrequerimento` INT NOT NULL,
  `objeto` VARCHAR(200) NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `data/hora_regis` DATETIME(6) NOT NULL,
  `obs` VARCHAR(200) NULL,
  `anexos` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(10) NOT NULL,
  `discente_matricula` BIGINT(15) NOT NULL,
  `idcurso` INT NOT NULL,
  PRIMARY KEY (`idrequerimento`),
  INDEX `fk_requerimento_discente1_idx` (`discente_matricula` ASC),
  INDEX `fk_requerimento_curso1_idx` (`idcurso` ASC),
  CONSTRAINT `fk_requerimento_discente1`
    FOREIGN KEY (`discente_matricula`)
    REFERENCES `login`.`discente` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requerimento_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `login`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`docente` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `requerimento_idrequerimento` INT NOT NULL,
  PRIMARY KEY (`requerimento_idrequerimento`),
  CONSTRAINT `fk_docente_requerimento1`
    FOREIGN KEY (`requerimento_idrequerimento`)
    REFERENCES `login`.`requerimento` (`idrequerimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`adm` (
  `cod_adm` INT(11) NOT NULL,
  `senha` INT(10) NULL,
  PRIMARY KEY (`cod_adm`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
