-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 15:22:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `mydb`.`discente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`discente` (
  `matricula` BIGINT(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `nome_aluno` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`coordenacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`coordenacao` (
  `cod_siape` BIGINT(11) NOT NULL,
  `id_coordenacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `coordenacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_siape`),
  UNIQUE INDEX `id_coordenacao_UNIQUE` (`id_coordenacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(50) NOT NULL,
  `cod_siape` BIGINT(11) NOT NULL,
  `discente_matricula` BIGINT(15) NOT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_departamento_idx` (`cod_siape` ASC),
  INDEX `fk_curso_discente1_idx` (`discente_matricula` ASC),
  CONSTRAINT `fk_curso_departamento`
    FOREIGN KEY (`cod_siape`)
    REFERENCES `projeto`.`coordenacao` (`cod_siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_discente1`
    FOREIGN KEY (`discente_matricula`)
    REFERENCES `projeto`.`discente` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`requerimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`requerimento` (
  `idrequerimento` INT NOT NULL AUTO_INCREMENT,
  `objeto` VARCHAR(200) NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `data/hora_regis` DATETIME(6) NOT NULL,
  `obs` VARCHAR(200) NULL,
  `anexos` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `turma` VARCHAR(10) NOT NULL,
  `discente_matricula` BIGINT(15) NOT NULL,
  `idcurso` INT NOT NULL,
  PRIMARY KEY (`idrequerimento`),
  INDEX `fk_requerimento_discente1_idx` (`discente_matricula` ASC),
  INDEX `fk_requerimento_curso1_idx` (`idcurso` ASC),
  CONSTRAINT `fk_requerimento_discente1`
    FOREIGN KEY (`discente_matricula`)
    REFERENCES `projeto`.`discente` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requerimento_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `projeto`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`docente` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `requerimento_idrequerimento` INT NOT NULL,
  PRIMARY KEY (`requerimento_idrequerimento`),
  CONSTRAINT `fk_docente_requerimento1`
    FOREIGN KEY (`requerimento_idrequerimento`)
    REFERENCES `projeto`.`requerimento` (`idrequerimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`adm` (
  `cod_adm` BIGINT(11) NOT NULL,
  `senha` INT(10) NOT NULL,
  PRIMARY KEY (`cod_adm`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
